import { useState } from "react";
import {
  Box,
  Typography,
  Paper,
  Accordion,
  AccordionSummary,
  AccordionDetails,
} from "@mui/material";

import ExpandMoreIcon from "@mui/icons-material/ExpandMore";

const faqs = [
  {
    question: "Who Can Use Betleaders?",
    answer:
      "Betleaders is a free, non-gambling platform open to users located in the United States aged 18 and older. Instead of real-money wagering, it pulls real odds from sportsbooks and allows users to simulate bets without risking money.",
  },
  {
    question: "What is a Betexpert?",
    answer:
      "A Betexpert is a user who shares their betting picks and strategies and can gain subscribers based on their performance.",
  },
  {
    question: "What is a Subscriber?",
    answer:
      "Subscribers follow Betexperts and receive their betting picks and insights.",
  },
  {
    question: "Can I be a Betexpert & Subscriber at the same time?",
    answer:
      "Yes. Users can both publish picks as a Betexpert and subscribe to other Betexperts.",
  },
  {
    question: 'What is the "Master Sportsbook"?',
    answer:
      "The Master Sportsbook aggregates odds from multiple sportsbooks to help users find the best value.",
  },
  {
    question: "Do I need to wager real money on the Master Sportsbook?",
    answer:
      "No. The platform uses simulated bets based on real sportsbook odds.",
  },
  {
    question: "How many sportsbooks does Betleaders pull odds from?",
    answer:
      "Betleaders aggregates odds from several major sportsbooks to ensure accurate comparisons.",
  },
  {
    question: "How can I get ranked on the leaderboards?",
    answer:
      "By creating bets and consistently performing well, users can climb the leaderboards.",
  },
  {
    question: "What % of subscriptions do Betexperts keep?",
    answer:
      "Betexperts receive a percentage of subscription revenue generated by their followers.",
  },
  {
    question: "Where do I receive the bet once I'm subscribed?",
    answer:
      "Subscribers receive picks through their dashboard notifications and updates.",
  },
];

function FaqSection() {
  const [expanded, setExpanded] = useState([]);

  const handleChange = (index) => (event, isExpanded) => {
    if (isExpanded) {
      setExpanded([...expanded, index]);
    } else {
      setExpanded(expanded.filter((i) => i !== index));
    }
  };

  return (
    <Box
      sx={{
        display: "flex",
        justifyContent: "center",
        p: 2,
      }}
    >
      <Paper
        sx={{
          border: "1px solid #e5e7eb",
          borderRadius: 3,
          boxShadow: 1,
          width: "100%",
          maxWidth: 1150,
          p: 3,
        }}
      >
        <Typography
          sx={{ color: "#2563eb", fontSize: "16px", fontWeight: 700, mb: 1 }}
        >
          Availability
        </Typography>

        <Typography
          fontWeight={"semibold"}
          mb={1}
          sx={{ fontSize: { sx: 20, md: "32px" } }}
        >
          Frequently asked questions
        </Typography>

        {faqs.map((faq, index) => (
          <Accordion
            key={index}
            expanded={expanded.includes(index)}
            onChange={handleChange(index)}
            sx={{
              border: "1px solid #e5e7eb",
              borderRadius: 2,
              mb: 1,
              boxShadow: "none",
              "&:before": { display: "none" },
            }}
          >
            <AccordionSummary expandIcon={<ExpandMoreIcon />}>
              <Typography fontSize={"16px"} fontWeight={"bold"}>
                {faq.question}
              </Typography>
            </AccordionSummary>

            <AccordionDetails>
              <Typography
                fontSize={"16px"}
                color="text.secondary"
                sx={{ width: { sx: "100%", md: "50%" } }}
              >
                {faq.answer}
              </Typography>
            </AccordionDetails>
          </Accordion>
        ))}
      </Paper>
    </Box>
  );
}

export default FaqSection;
